services:

  db:
    image: mysql:8.1
    container_name: ${DOCKER_PREFIX}_db
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

  wp:
    container_name: ${DOCKER_PREFIX}_app
    depends_on:
      - db
    restart: always
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: silvergama/wordpress-xdebug:latest
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:${MYSQL_PORT}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
    ports:
      - "${SITE_PORT}:80"
    volumes:
      - "./html:/var/www/html"
      - "./docker/logs/xdebug.log:/tmp/xdebug.log"
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    networks:
      - app-network

  # wait:
  #   image: "waisbrot/wait"
  #   restart: "no"
  #   environment:
  #     TARGETS: "db:3306"
  #     TIMEOUT: 60
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${DOCKER_PREFIX}_pma
    environment:
      UPLOAD_LIMIT: 100000000
    #   PMA_HOST: db
    depends_on:
      - db
    ports:
        - 88:80
    networks:
      - app-network

# volumes:
#   db:

networks:
  app-network:
    driver: bridge
